# Generated by Django 5.0 on 2023-12-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
    ]
